/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 table1.gltf 
Author: yryabchenko (https://sketchfab.com/yryabchenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/table-1132fa2850a24917892733566bd68e74
Title: Table
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { ExtendedColors, Overwrite, NodeProps, NonFunctionKeys, Vector3, Euler, Matrix4, Quaternion, Layers } from "@react-three/fiber";
import { EventHandlers } from "@react-three/fiber/dist/declarations/src/core/events";
import { JSX } from "react/jsx-runtime";

export default function Model(props: JSX.IntrinsicAttributes & Omit<ExtendedColors<Overwrite<Partial<THREE.Group<THREE.Object3DEventMap>>, NodeProps<THREE.Group<THREE.Object3DEventMap>, typeof THREE.Group>>>, NonFunctionKeys<{ position?: Vector3; up?: Vector3; scale?: Vector3; rotation?: Euler; matrix?: Matrix4; quaternion?: Quaternion; layers?: Layers; dispose?: (() => void) | null; }>> & { position?: Vector3; up?: Vector3; scale?: Vector3; rotation?: Euler; matrix?: Matrix4; quaternion?: Quaternion; layers?: Layers; dispose?: (() => void) | null; } & EventHandlers) {
  const { nodes, materials } = useGLTF("/table1/table1.gltf");
  const nodemesh = nodes.pCylinder6_blinn1_0 as THREE.Mesh
  return (
    <group {...props} dispose={null} >
      <mesh
        geometry={nodemesh.geometry}
        material={materials.blinn1}
        position={[-2, -0.45, -1.5]}
        scale={0.5}
      />
    </group>
  );
}

useGLTF.preload("/table1.gltf");
