/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chair.gltf 
*/

import { useGLTF } from "@react-three/drei";
import { ExtendedColors, Overwrite, NodeProps, NonFunctionKeys, Vector3, Euler, Matrix4, Quaternion, Layers } from "@react-three/fiber";
import { EventHandlers } from "@react-three/fiber/dist/declarations/src/core/events";
import { JSX } from "react/jsx-runtime";
import * as THREE from "three";

export default function Model(props: JSX.IntrinsicAttributes & Omit<ExtendedColors<Overwrite<Partial<THREE.Group<THREE.Object3DEventMap>>, NodeProps<THREE.Group<THREE.Object3DEventMap>, typeof THREE.Group>>>, NonFunctionKeys<{ position?: Vector3; up?: Vector3; scale?: Vector3; rotation?: Euler; matrix?: Matrix4; quaternion?: Quaternion; layers?: Layers; dispose?: (() => void) | null; }>> & { position?: Vector3; up?: Vector3; scale?: Vector3; rotation?: Euler; matrix?: Matrix4; quaternion?: Quaternion; layers?: Layers; dispose?: (() => void) | null; } & EventHandlers) {
  const { nodes, materials } = useGLTF("/chair/chair.gltf");
  const meshNode = nodes.wjglah2s_LOD0_TIER2_000 as THREE.Mesh;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={meshNode.geometry}
        material={materials.MI_wjglah2s}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
        position={[-2, -0.5, -3.5]}
      />
    </group>
  );
}

useGLTF.preload("/chair.gltf");
